spring.datasource.url=jdbc:mysql://localhost:3306/tables_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=YWdyaTdiNDZoM3M3bTludngxZzdrdXQzMmRmaDc5MDg=
spring.app.jwtExpirationMs=300000000

logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

